### ISSUE TITLE
Project Outline: Feedback

### ISSUE THREAD

**Issue by lindskelsey** [lorithurman87/liftoff-assignments#2]
Your project is well-defined, and I think the scope is reasonable for an 8 week project.  Your features have a good balance of things that will feel familiar, as we did them on other project, and things that are new.

I would challenge you as part of a stretch goal to consider adding in a technology that is brand new to you. Incorporating an existing API, like you mentioned, would be one great option. You could also consider expanding your CSS knowledge by learning BootStrap, or using newer CSS tools like Flexbox or CSS Grid. I would not include these in your MVP, but something to consider when you reach that MVP!

**Comment by lorithurman87** [comment]
thanks. will definitely consider it. if I reach what we have discussed so far I was also considering trying to learn some basics in JavaScript and implementing them. but I didn't want to add that yet to see how I do in the next couple weeks. I'm open to suggestions :)
